security:
    role_hierarchy:
        ROLE_DEVELOPER: [ROLE_ADMIN, ROLE_CAN_SWITCH_USER]
        ROLE_ADMIN: [ROLE_CHIEF_EDITOR]
        ROLE_CHIEF_EDITOR: [ROLE_EDITOR]
        ROLE_EDITOR: [ROLE_USER]
        # ROLE_USER is assigned to Bolt Entity Users if no roles have been set
        ROLE_USER: []
        ROLE_WEBSERVICE: []

    enable_authenticator_manager: true

    password_hashers:
        Bolt\Entity\User: auto
        App\Entity\Customer:
            algorithm: auto


    providers:
        database_users:
            entity:
                class: Bolt\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Customer
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            pattern: ^/api
            http_basic: { provider: database_users }
        
        main:
            pattern: ^/
            user_checker: Bolt\Security\UserChecker
            switch_user: { role: CAN_SWITCH_USER, provider: database_users }
            entry_point: Bolt\Security\AuthenticationEntryPointRedirector

            custom_authenticators:
                - Bolt\Security\LoginFormAuthenticator

            logout:
                path: bolt_logout
                target: bolt_login
                invalidate_session: false

            remember_me:
                secret: '%kernel.secret%'
                lifetime: '%bolt.remember_lifetime%'
                remember_me_parameter: login[remember_me]

    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - { path: '^%bolt.backend_url%/login$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^%bolt.backend_url%/reset-password', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # backend_url: require users to actually be logged in (not remember-me) - detailed permissions are
        # handled by Voters
        - { path: '^%bolt.backend_url%/api', roles: ADMIN_API_ACCESS } # handled by voter
        - { path: '^/(%app_locales%)%bolt.backend_url%/api', roles: ADMIN_API_ACCESS } # handled by voter
        - { path: '^%bolt.backend_url%/_trans', roles: ADMIN_TRANSLATE_ACCESS } # handled by voter
        - { path: '^/(%app_locales%)%bolt.backend_url%/_trans', roles: ADMIN_TRANSLATE_ACCESS } # handled by voter
        - { path: '^%bolt.backend_url%', roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: '^/(%app_locales%)%bolt.backend_url%', roles: IS_AUTHENTICATED_REMEMBERED }
